print('To start fill the dimensions ')
l=input('Enter the lenth of a cuboid: ')
l=float(l)
b=input('Enter the breath of a cuboid: ')
b=float(b)
h=input('Enter the height of a cuboid: ')
h=float(h)
area=2*(l*b+b*h+h*l)
print('The surface area of that cuboid is: ',area)